"""
p3p_harness.py
==============

A rigorous, pluggable Monte Carlo test harness for P3P (Perspective-3-Point)
pose solvers.

Pipeline
--------
1. Ground truth: points are generated directly in the CAMERA frame according
   to a chosen geometric configuration (standard frustum, collinear, planar
   circle sitting on the P3P "danger cylinder", symmetric triangle, extreme
   depth spread, or near-coincident projections). A random rigid transform
   (R_gt, t_gt) is drawn, and the camera-frame points are mapped back into a
   WORLD frame via X_world = R_gt^T @ (X_cam - t_gt). This guarantees every
   point is in front of the camera by construction, for every configuration,
   without any rejection sampling.
2. Projection + noise: the camera-frame points are projected through K to
   clean pixel coordinates, then zero-mean Gaussian noise at a chosen sigma
   (in pixels) is added.
3. Solve: a solver plugin receives (X_world (3,3), noisy 2D obs (3,2), K) and
   returns a list of up to 4 (R, t) candidate poses -- exactly the P3P
   interface. A 4th, independent validation point (also generated by the
   same configuration, kept noise-free) is used to disambiguate between
   returned candidates, exactly as you would with a real 4th correspondence.
4. Score: geodesic rotation error, translation error (%), reprojection RMSE
   on the 3 solved points, plus a running "numerical stability index" that
   separately counts solver exceptions, empty return values, and NaN/Inf
   candidates -- these are informative failure modes in their own right and
   are never silently folded into the accuracy numbers.

Everything (configurations, solvers, noise levels) is a plain Python
dict/registry, so this is meant to be extended, not just run as-is.

Dependencies: numpy is required. pandas and OpenCV (cv2) are optional --
without cv2 you simply won't have the two built-in reference solvers
registered (you can still register your own), and without pandas the
summary prints as plain text instead of a formatted table.
"""

import time
import traceback
from dataclasses import dataclass, field
from typing import Callable, Dict, List, Optional, Tuple

import numpy as np

try:
    import cv2
    _HAVE_CV2 = True
except ImportError:
    _HAVE_CV2 = False

try:
    import pandas as pd
    _HAVE_PANDAS = True
except ImportError:
    _HAVE_PANDAS = False


# ---------------------------------------------------------------------------
# Camera model
# ---------------------------------------------------------------------------

def make_intrinsics(fx: float = 800.0, fy: float = 800.0,
                     cx: float = 320.0, cy: float = 240.0) -> np.ndarray:
    return np.array([[fx, 0.0, cx],
                      [0.0, fy, cy],
                      [0.0, 0.0, 1.0]], dtype=np.float64)


def project(points_cam: np.ndarray, K: np.ndarray) -> np.ndarray:
    """Pinhole-project (N,3) camera-frame points through K to (N,2) pixels."""
    z = points_cam[:, 2:3]
    proj = (K @ points_cam.T).T
    return proj[:, :2] / z


def add_gaussian_noise(points_2d: np.ndarray, sigma: float,
                        rng: np.random.Generator) -> np.ndarray:
    if sigma <= 0:
        return points_2d.copy()
    return points_2d + rng.normal(scale=sigma, size=points_2d.shape)


# ---------------------------------------------------------------------------
# Random rigid transforms (pure numpy -- no scipy dependency)
# ---------------------------------------------------------------------------

def random_rotation(rng: np.random.Generator) -> np.ndarray:
    """Uniform random rotation matrix via a random unit quaternion."""
    q = rng.normal(size=4)
    q /= np.linalg.norm(q)
    w, x, y, z = q
    return np.array([
        [1 - 2 * (y * y + z * z), 2 * (x * y - z * w), 2 * (x * z + y * w)],
        [2 * (x * y + z * w), 1 - 2 * (x * x + z * z), 2 * (y * z - x * w)],
        [2 * (x * z - y * w), 2 * (y * z + x * w), 1 - 2 * (x * x + y * y)],
    ])


def random_translation(rng: np.random.Generator,
                        low: float = -1.0, high: float = 1.0) -> np.ndarray:
    return rng.uniform(low, high, size=3)


def camera_to_world(points_cam: np.ndarray, R_gt: np.ndarray,
                     t_gt: np.ndarray) -> np.ndarray:
    """Invert X_cam = R_gt @ X_world + t_gt."""
    return (R_gt.T @ (points_cam - t_gt).T).T


# ---------------------------------------------------------------------------
# Point-configuration generators.
#
# Each returns (solve_points_cam (3,3), validation_point_cam (3,)) -- all in
# the CAMERA frame, all with positive Z by construction. The harness handles
# turning these into a world-frame P3P problem via camera_to_world().
# ---------------------------------------------------------------------------

def config_standard(rng: np.random.Generator) -> Tuple[np.ndarray, np.ndarray]:
    """Baseline case: points scattered through a typical viewing frustum."""
    pts = np.empty((4, 3))
    pts[:, 0] = rng.uniform(-2.0, 2.0, size=4)
    pts[:, 1] = rng.uniform(-2.0, 2.0, size=4)
    pts[:, 2] = rng.uniform(2.0, 10.0, size=4)
    return pts[:3], pts[3]


def config_collinear(rng: np.random.Generator) -> Tuple[np.ndarray, np.ndarray]:
    """The 3 solved points lie exactly on one line -- classically singular."""
    origin = np.array([rng.uniform(-1, 1), rng.uniform(-1, 1), rng.uniform(4, 8)])
    direction = rng.normal(size=3)
    direction /= np.linalg.norm(direction)
    offsets = rng.uniform(0.3, 2.0, size=3) * rng.choice([-1, 1], size=3)
    pts = origin + np.outer(offsets, direction)
    # Validation point off the line so disambiguation is still meaningful.
    val = origin + rng.normal(scale=0.5, size=3) + np.array([0, 0, 1.0])
    return pts, val


def config_planar_circular(rng: np.random.Generator) -> Tuple[np.ndarray, np.ndarray]:
    """
    3 points on a circle, with the camera center placed ON the classical
    P3P "danger cylinder" -- the vertical cylinder through that circle. This
    is the textbook configuration that produces coincident/ambiguous roots.
    The camera center in this generator's own frame is the origin, so we
    build points around a circle whose axis passes through the origin's
    (x, y); i.e. the origin's (x, y) lies on the circle itself.
    """
    radius = rng.uniform(1.0, 3.0)
    z_plane = rng.uniform(4.0, 8.0)
    # Place the circle so that (0, 0) -- the camera center's (x, y) -- sits
    # exactly on it: center the circle at (radius, 0).
    center_xy = np.array([radius, 0.0])
    thetas = rng.uniform(0, 2 * np.pi, size=3)
    pts = np.stack([
        center_xy[0] + radius * np.cos(thetas),
        center_xy[1] + radius * np.sin(thetas),
        np.full(3, z_plane),
    ], axis=1)
    val_theta = rng.uniform(0, 2 * np.pi)
    val = np.array([center_xy[0] + radius * np.cos(val_theta),
                     center_xy[1] + radius * np.sin(val_theta),
                     z_plane + 1.0])
    return pts, val


def config_symmetric_triangle(rng: np.random.Generator) -> Tuple[np.ndarray, np.ndarray]:
    """Strict equilateral triangle, arbitrary orientation and depth."""
    radius = rng.uniform(0.5, 2.0)
    z_plane = rng.uniform(3.0, 9.0)
    center_xy = rng.uniform(-1.0, 1.0, size=2)
    base_theta = rng.uniform(0, 2 * np.pi)
    thetas = base_theta + np.array([0.0, 2 * np.pi / 3, 4 * np.pi / 3])
    pts = np.stack([
        center_xy[0] + radius * np.cos(thetas),
        center_xy[1] + radius * np.sin(thetas),
        np.full(3, z_plane),
    ], axis=1)
    val = np.array([center_xy[0], center_xy[1], z_plane + 2.0])
    return pts, val


def config_extreme_depth(rng: np.random.Generator) -> Tuple[np.ndarray, np.ndarray]:
    """One very near point, two far points -- stresses coefficient scaling."""
    near = np.array([rng.uniform(-0.05, 0.05), rng.uniform(-0.05, 0.05),
                      rng.uniform(0.1, 0.3)])
    far1 = np.array([rng.uniform(-20, 20), rng.uniform(-20, 20),
                      rng.uniform(100, 150)])
    far2 = np.array([rng.uniform(-20, 20), rng.uniform(-20, 20),
                      rng.uniform(100, 150)])
    val = np.array([rng.uniform(-10, 10), rng.uniform(-10, 10),
                     rng.uniform(50, 100)])
    return np.stack([near, far1, far2]), val


def config_near_coincident(rng: np.random.Generator) -> Tuple[np.ndarray, np.ndarray]:
    """
    3 points nearly along the same camera ray, at different depths, with a
    sub-pixel-scale angular perturbation -- their projections land within a
    fraction of a pixel of each other before noise is even added.
    """
    bearing = rng.normal(size=3)
    bearing /= np.linalg.norm(bearing)
    depths = rng.uniform(3.0, 9.0, size=3)
    # Perpendicular jitter tiny enough that, at these depths and f~800,
    # the projected separation is well under a pixel.
    perp = rng.normal(size=3)
    perp -= perp.dot(bearing) * bearing
    perp /= (np.linalg.norm(perp) + 1e-12)
    jitter_scale = 1e-4
    pts = np.stack([
        d * bearing + jitter_scale * rng.normal() * perp for d in depths
    ])
    val = 6.0 * bearing + 0.5 * perp
    return pts, val


CONFIGS: Dict[str, Callable[[np.random.Generator], Tuple[np.ndarray, np.ndarray]]] = {
    "standard": config_standard,
    "collinear": config_collinear,
    "planar_circular": config_planar_circular,
    "symmetric_triangle": config_symmetric_triangle,
    "extreme_depth": config_extreme_depth,
    "near_coincident": config_near_coincident,
}


# ---------------------------------------------------------------------------
# Solver registry
#
# A solver is any callable: (points_world (3,3), points_2d (3,2), K (3,3))
#   -> List[Tuple[R (3,3), t (3,)]]
# It may raise -- the harness catches and records that as an exception, not
# a crash. Returning [] is treated as "no solution found" (also recorded).
# ---------------------------------------------------------------------------

SOLVERS: Dict[str, Callable] = {}



def register_solver(name: str, fn: Callable) -> None:
    SOLVERS[name] = fn


# ---------------------------------------------------------------------------
# tetraLen P3P adapter
# ---------------------------------------------------------------------------

try:
    from tetralen import tetraLen

    def _tetralen_p3p(points_world: np.ndarray,
                       points_2d: np.ndarray,
                       K: np.ndarray) -> List[Tuple[np.ndarray, np.ndarray]]:

        A, B, C = points_world

        # Camera bearing rays from pixel coordinates.
        Kinv = np.linalg.inv(K)
        uv1 = np.column_stack([
            points_2d,
            np.ones(3)
        ])

        rays = (Kinv @ uv1.T).T
        rays /= np.linalg.norm(rays, axis=1, keepdims=True)

        # Known world-space triangle.
        x1 = np.linalg.norm(A - B)   # AB
        x2 = np.linalg.norm(A - C)   # AC
        x3 = np.linalg.norm(B - C)   # BC

        # Angles at the camera D.
        def angle_between(u, v):
            c = np.clip(np.dot(u, v), -1.0, 1.0)
            return np.arccos(c)

        ph1 = angle_between(rays[0], rays[1])  # A-D-B
        ph2 = angle_between(rays[0], rays[2])  # A-D-C
        ph3 = angle_between(rays[1], rays[2])  # B-D-C

        result = tetraLen(
            x1, x2, x3,
            ph1, ph2, ph3,
            precision=4
        )

        # tetraLen returns:
        #   [AD, BD, CD]
        solutions = result[0] if isinstance(result, tuple) else result

        candidates = []

        for sol in solutions:
            if len(sol) != 3:
                continue

            distances = np.asarray([sol[1], sol[0], sol[2]], dtype=np.float64) 

            if not np.all(np.isfinite(distances)):
                continue

            if np.any(distances <= 0):
                continue

            # Reconstruct camera-frame points.
            X_cam = rays * distances[:, None]

            if not np.all(np.isfinite(X_cam)):
                continue

            # Recover rigid transform:
            #
            # X_cam = R @ X_world + t
            #
            # Kabsch / orthogonal Procrustes.

            world_centroid = np.mean(points_world, axis=0)
            cam_centroid = np.mean(X_cam, axis=0)

            Xw = points_world - world_centroid
            Xc = X_cam - cam_centroid

            H = Xw.T @ Xc

            U, _, Vt = np.linalg.svd(H)

            R = Vt.T @ U.T

            # Enforce proper rotation.
            if np.linalg.det(R) < 0:
                Vt[-1, :] *= -1
                R = Vt.T @ U.T

            t = cam_centroid - R @ world_centroid

            if not (
                np.all(np.isfinite(R)) and
                np.all(np.isfinite(t))
            ):
                continue

            candidates.append((R, t))

        return candidates

    register_solver("tetraLen", _tetralen_p3p)

except ImportError:
    pass

if _HAVE_CV2:
    def _cv2_p3p(points_world: np.ndarray, points_2d: np.ndarray,
                 K: np.ndarray, flag: int) -> List[Tuple[np.ndarray, np.ndarray]]:
        obj = points_world.reshape(-1, 1, 3).astype(np.float64)
        img = points_2d.reshape(-1, 1, 2).astype(np.float64)
        dist = np.zeros(4)
        retval, rvecs, tvecs = cv2.solveP3P(obj, img, K, dist, flags=flag)
        candidates = []
        if retval:
            for rvec, tvec in zip(rvecs, tvecs):
                R, _ = cv2.Rodrigues(rvec)
                candidates.append((R, tvec.reshape(3)))
        return candidates

    register_solver("Kneip (OpenCV P3P)",
                     lambda pw, p2, K: _cv2_p3p(pw, p2, K, cv2.SOLVEPNP_P3P))
    register_solver("AP3P (OpenCV)",
                     lambda pw, p2, K: _cv2_p3p(pw, p2, K, cv2.SOLVEPNP_AP3P))


# ---------------------------------------------------------------------------
# Metrics
# ---------------------------------------------------------------------------

def rotation_error_deg(R_est: np.ndarray, R_gt: np.ndarray) -> float:
    R_diff = R_est.T @ R_gt
    cos_theta = np.clip((np.trace(R_diff) - 1.0) / 2.0, -1.0, 1.0)
    return float(np.degrees(np.arccos(cos_theta)))


def translation_error_pct(t_est: np.ndarray, t_gt: np.ndarray) -> float:
    denom = np.linalg.norm(t_gt)
    if denom < 1e-12:
        denom = 1e-12
    return float(np.linalg.norm(t_est - t_gt) / denom * 100.0)


def reprojection_rmse(points_world: np.ndarray, observed_2d: np.ndarray,
                       R_est: np.ndarray, t_est: np.ndarray, K: np.ndarray) -> float:
    X_cam = (R_est @ points_world.T).T + t_est.reshape(1, 3)
    proj = project(X_cam, K)
    return float(np.sqrt(np.mean(np.sum((proj - observed_2d) ** 2, axis=1))))


# ---------------------------------------------------------------------------
# Monte Carlo runner
# ---------------------------------------------------------------------------

@dataclass
class TrialSummary:
    config: str
    solver: str
    sigma: float
    n_iters: int
    n_success: int = 0
    n_exception: int = 0
    n_empty: int = 0
    n_nonfinite: int = 0
    rot_errs: List[float] = field(default_factory=list)
    trans_errs: List[float] = field(default_factory=list)
    reproj_rmses: List[float] = field(default_factory=list)
    elapsed_s: float = 0.0

    def as_row(self) -> dict:
        def stats(arr, pctl=95):
            if not arr:
                return (float("nan"),) * 3
            a = np.asarray(arr)
            return (float(np.mean(a)), float(np.median(a)), float(np.percentile(a, pctl)))

        rot_mean, rot_med, rot_p95 = stats(self.rot_errs)
        tr_mean, tr_med, tr_p95 = stats(self.trans_errs)
        rp_mean, rp_med, rp_p95 = stats(self.reproj_rmses)

        return {
            "config": self.config,
            "solver": self.solver,
            "sigma_px": self.sigma,
            "n": self.n_iters,
            "success_rate": self.n_success / self.n_iters,
            "exception_rate": self.n_exception / self.n_iters,
            "empty_rate": self.n_empty / self.n_iters,
            "nonfinite_rate": self.n_nonfinite / self.n_iters,
            "rot_err_deg_mean": rot_mean,
            "rot_err_deg_median": rot_med,
            "rot_err_deg_p95": rot_p95,
            "trans_err_pct_mean": tr_mean,
            "trans_err_pct_median": tr_med,
            "trans_err_pct_p95": tr_p95,
            "reproj_rmse_px_mean": rp_mean,
            "reproj_rmse_px_median": rp_med,
            "reproj_rmse_px_p95": rp_p95,
            "us_per_iter": self.elapsed_s / self.n_iters * 1e6,
        }


def run_trial(config_name: str, solver_name: str, sigma: float, n_iters: int,
              K: np.ndarray, seed: int) -> TrialSummary:
    rng = np.random.default_rng(seed)
    gen = CONFIGS[config_name]
    solver = SOLVERS[solver_name]
    summary = TrialSummary(config_name, solver_name, sigma, n_iters)

    t0 = time.perf_counter()
    for _ in range(n_iters):
        pts_cam, val_cam = gen(rng)
        R_gt = random_rotation(rng)
        t_gt = random_translation(rng)

        X_world = camera_to_world(pts_cam, R_gt, t_gt)
        X_world_val = camera_to_world(val_cam.reshape(1, 3), R_gt, t_gt)[0]

        obs_clean = project(pts_cam, K)
        obs_noisy = add_gaussian_noise(obs_clean, sigma, rng)
        val_2d_clean = project(val_cam.reshape(1, 3), K)[0]

        try:
            candidates = solver(X_world, obs_noisy, K)
        except Exception:
            summary.n_exception += 1
            continue

        if not candidates:
            summary.n_empty += 1
            continue

        best_pose, best_err = None, np.inf
        for R_est, t_est in candidates:
            if not (np.all(np.isfinite(R_est)) and np.all(np.isfinite(t_est))):
                continue
            X_val_cam_est = R_est @ X_world_val + t_est
            if X_val_cam_est[2] <= 0:
                continue
            proj_val = project(X_val_cam_est.reshape(1, 3), K)[0]
            err = float(np.linalg.norm(proj_val - val_2d_clean))
            if err < best_err:
                best_err, best_pose = err, (R_est, t_est)

        if best_pose is None:
            summary.n_nonfinite += 1
            continue

        R_est, t_est = best_pose
        summary.rot_errs.append(rotation_error_deg(R_est, R_gt))
        summary.trans_errs.append(translation_error_pct(t_est, t_gt))
        summary.reproj_rmses.append(reprojection_rmse(X_world, obs_noisy, R_est, t_est, K))
        summary.n_success += 1

    summary.elapsed_s = time.perf_counter() - t0
    return summary


def run_suite(configs: Optional[List[str]] = None,
              solvers: Optional[List[str]] = None,
              sigmas: Tuple[float, ...] = (0.1, 0.5, 1.0, 3.0),
              n_iters: int = 3000,
              K: Optional[np.ndarray] = None,
              seed: int = 12345) -> List[TrialSummary]:
    configs = configs or list(CONFIGS.keys())
    solvers = solvers or list(SOLVERS.keys())
    K = K if K is not None else make_intrinsics()

    if not solvers:
        raise RuntimeError(
            "No solvers registered. Install opencv-python for the built-in "
            "reference solvers, or call register_solver(name, fn) with your "
            "own P3P implementation before calling run_suite()."
        )

    results = []
    combo = 0
    total = len(configs) * len(solvers) * len(sigmas)
    for config_name in configs:
        for solver_name in solvers:
            for sigma in sigmas:
                combo += 1
                results.append(
                    run_trial(config_name, solver_name, sigma, n_iters, K,
                              seed=seed + combo)
                )
    return results


def summarize(results: List[TrialSummary]):
    rows = [r.as_row() for r in results]
    if _HAVE_PANDAS:
        df = pd.DataFrame(rows)
        pd.set_option("display.width", 160)
        pd.set_option("display.max_columns", 20)
        pd.set_option("display.float_format", lambda v: f"{v:.4g}")
        return df
    return rows


def print_summary(results: List[TrialSummary]) -> None:
    summary = summarize(results)
    if _HAVE_PANDAS:
        cols = ["config", "solver", "sigma_px", "success_rate",
                "exception_rate", "empty_rate", "nonfinite_rate",
                "rot_err_deg_median", "trans_err_pct_median",
                "reproj_rmse_px_median", "us_per_iter"]
        print(summary[cols].to_string(index=False))
    else:
        header = ["config", "solver", "sigma", "succ%", "exc%", "empty%",
                   "nonfin%", "rot_med", "trans_med%", "reproj_med", "us/it"]
        print(" | ".join(header))
        for row in summary:
            print(" | ".join([
                row["config"], row["solver"], f"{row['sigma_px']:.2f}",
                f"{row['success_rate']*100:.1f}", f"{row['exception_rate']*100:.2f}",
                f"{row['empty_rate']*100:.2f}", f"{row['nonfinite_rate']*100:.2f}",
                f"{row['rot_err_deg_median']:.4g}",
                f"{row['trans_err_pct_median']:.4g}",
                f"{row['reproj_rmse_px_median']:.4g}",
                f"{row['us_per_iter']:.1f}",
            ]))


if __name__ == "__main__":
    import argparse

    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--n-iters", type=int, default=3000,
                         help="Monte Carlo iterations per (config, solver, sigma) bracket.")
    parser.add_argument("--configs", nargs="*", default=None,
                         help=f"Subset of {list(CONFIGS.keys())}")
    parser.add_argument("--solvers", nargs="*", default=None,
                         help=f"Subset of {list(SOLVERS.keys())}")
    parser.add_argument("--sigmas", nargs="*", type=float, default=[0.1, 0.5, 1.0, 3.0])
    parser.add_argument("--seed", type=int, default=12345)
    args = parser.parse_args()

    if not SOLVERS:
        print("No solvers registered (opencv-python not found). "
              "Register a solver via register_solver() and re-run, e.g.:\n"
              "  from p3p_harness import register_solver, run_suite, print_summary\n"
              "  register_solver('MySolver', my_p3p_fn)\n"
              "  print_summary(run_suite())")
    else:
        results = run_suite(configs=args.configs, solvers=args.solvers,
                             sigmas=tuple(args.sigmas), n_iters=args.n_iters,
                             seed=args.seed)
        print_summary(results)
